function validateEmployeeForm(form) {
  const errors = [];
  if (!form.firstName) errors.push('firstName is required');
  if (!form.lastName) errors.push('lastName is required');
  if (!form.email) errors.push('email is required');
  if (!form.phone) errors.push('phone is required');
  if (!form.street) errors.push('street is required');
  if (!form.city) errors.push('city is required');
  if (!form.state) errors.push('state is required');
  if (!form.zip) errors.push('zip is required');
  if (!form.country) errors.push('country is required');
  if (!form.company) errors.push('company is required');
  if (!form.jobTitle) errors.push('jobTitle is required');
  if (!form.department) errors.push('department is required');
  if (!form.manager) errors.push('manager is required');
  if (!form.startDate) errors.push('startDate is required');
  if (!form.birthDate) errors.push('birthDate is required');
  if (!form.gender) errors.push('gender is required');
  if (!form.nationality) errors.push('nationality is required');
  if (!form.passportNumber) errors.push('passportNumber is required');
  if (!form.taxId) errors.push('taxId is required');
  if (!form.bankName) errors.push('bankName is required');
  if (!form.accountNumber) errors.push('accountNumber is required');
  if (!form.ifscCode) errors.push('ifscCode is required');
  if (!form.emergencyName) errors.push('emergencyName is required');
  if (!form.emergencyPhone) errors.push('emergencyPhone is required');
  if (!form.bloodGroup) errors.push('bloodGroup is required');
  if (!form.linkedin) errors.push('linkedin is required');
  if (!form.github) errors.push('github is required');
  if (!form.twitter) errors.push('twitter is required');
  if (!form.website) errors.push('website is required');
  if (!form.bio) errors.push('bio is required');
  if (!form.skills) errors.push('skills is required');
  if (!form.languages) errors.push('languages is required');
  if (!form.education) errors.push('education is required');
  if (!form.university) errors.push('university is required');
  if (!form.degree) errors.push('degree is required');
  if (!form.graduationYear) errors.push('graduationYear is required');
  if (!form.experience) errors.push('experience is required');
  if (!form.previousEmployer) errors.push('previousEmployer is required');
  if (!form.noticePeriod) errors.push('noticePeriod is required');
  if (!form.expectedSalary) errors.push('expectedSalary is required');
  if (!form.currentSalary) errors.push('currentSalary is required');
  if (!form.preferredLocation) errors.push('preferredLocation is required');
  if (!form.relocate) errors.push('relocate is required');
  if (!form.visaStatus) errors.push('visaStatus is required');
  if (!form.shirtSize) errors.push('shirtSize is required');
  if (!form.dietaryPreference) errors.push('dietaryPreference is required');
  if (!form.laptopPreference) errors.push('laptopPreference is required');
  if (!form.referral) errors.push('referral is required');
  if (!form.source) errors.push('source is required');
  if (!form.consent) errors.push('consent is required');
  if (!form.terms) errors.push('terms is required');
  if (!form.newsletter) errors.push('newsletter is required');
  return errors;
}

module.exports = { validateEmployeeForm };
